# Generated by Django 4.2.6 on 2023-10-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='Ships.sites')),
                ('takeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='Ships.sites')),
            ],
        ),
    ]
